#pragma once

// CORTEX A8

#define CONFIG_LITTLE_ENDIAN
#define CONFIG_ARM
#define CONFIG_ARMV7_A
#define CONFIG_CPU_AARCH32_CORTEX_A

#define CONFIG_CPU_HAS_VFP          1
#define CONFIG_CPU_HAS_FPU          1
#define CONFIG_FPU
#define CONFIG_CPU_HAS_MMU          1
#define CONFIG_ARM_MMU
#define CONFIG_CPU_HAS_MPU          1
#define CONFIG_ARM_MPU

// MISC
#define CONFIG_SMP
#define CONFIG_ASSERT
#define CONFIG_ASSERT_LEVEL 1
#define CONFIG_PRINTK
#define CONFIG_PRINTK_SYNC


#define CONFIG_SYS_CLOCK_EXISTS
#define CONFIG_THREAD_STACK_INFO
#define CONFIG_THREAD_NAME
#define CONFIG_THREAD_MAX_NAME_LEN 10
#define CONFIG_ERRNO
#define CONFIG_STACK_SENTINEL